### ISSUE TITLE
Shipment tracking in shipcloud

### ISSUE THREAD

**Issue by ayushkanoongo** [shipcloud/shipcloud-ruby#52]
My question is:-- 
1. How can I track a shipment in shipcloud?
2. Is there any demo tracking number present to get tracking information for testing purposes?

**Comment by andrecedik** [comment]
Hey @ayushkanoongo shipments are tracked automatically when you create the via the `shipment` endpoint. You can also create a tracker for tracking shipments that weren't created through shipcloud.

Unfortunately there is currently no way to get or set updated tracking information on the sandbox systems.
